import { Router } from 'express';
import { enforceMaintenanceMode } from '../middleware/enforceMaintenanceMode.js';
import { authRouter } from './auth.routes.js';
import { verificationRouter } from './verification.routes.js';
import { adminAuthRouter } from './admin/auth.routes.js';
import { adminRolesRouter } from './admin/roles.routes.js';
import { adminSystemUsersRouter } from './admin/system-users.routes.js';
import { adminShiftsRouter } from './admin/shifts.routes.js';
import { adminCustomersRouter } from './admin/customers.routes.js';
import { adminBlogsRouter } from './admin/blogs.routes.js';
import { adminWalletsRouter } from './admin/wallets.routes.js';
import { adminPayAccountsRouter } from './admin/payAccounts.routes.js';
import { adminPaymentMethodsRouter } from './admin/paymentMethods.routes.js';
import { adminCurrencyTypesRouter } from './admin/currencyTypes.routes.js';
import { adminUserCountDisplayRouter } from './admin/userCountDisplay.routes.js';
import { adminRatesRouter } from './admin/rates.routes.js';
import { adminDepositsRouter } from './admin/deposits.routes.js';
import { adminWithdrawalsRouter } from './admin/withdrawals.routes.js';
import { adminScammersRouter } from './admin/scammers.routes.js';
import { adminRejectReasonsRouter } from './admin/reject-reasons.routes.js';
import { adminNotificationsRouter } from './admin/notifications.routes.js';
import { adminLoyaltyRouter } from './admin/loyalty.routes.js';
import { adminHelpTicketsRouter } from './admin/help-tickets.routes.js';
import { adminPromotionalBannersRouter } from './admin/promotional-banners.routes.js';
import { adminVideoTutorialsRouter } from './admin/video-tutorials.routes.js';
import { adminLoyaltyMembershipTiersRouter } from './admin/loyalty-membership-tiers.routes.js';
import { adminDashboardRouter } from './admin/dashboard.routes.js';
import { adminPerformanceRouter } from './admin/performance.routes.js';
import { adminWebsiteLogosRouter } from './admin/website-logos.routes.js';
import { adminMaintenanceModeRouter } from './admin/maintenanceMode.routes.js';
import { adminMessageTemplatesRouter } from './admin/message-templates.routes.js';
import { adminBulkSmsRouter } from './admin/bulk-sms.routes.js';
import { publicCommunityStatsRouter } from './public/community-stats.routes.js';
import { publicHelpTicketsRouter } from './public/help-tickets.routes.js';
import { publicPromotionalBannersRouter } from './public/promotional-banners.routes.js';
import { publicVideoTutorialsRouter } from './public/video-tutorials.routes.js';
import { publicLoyaltyMembershipTiersRouter } from './public/loyalty-membership-tiers.routes.js';
import { healthRouter } from './health.routes.js';
import { userDashboardRouter } from './user/dashboard.routes.js';
import { userDepositsRouter } from './user/deposits.routes.js';
import { userWithdrawalsRouter } from './user/withdrawals.routes.js';
import { userPaymentAccountsRouter } from './user/payment-accounts.routes.js';
import { userProfileRouter } from './user/profile.routes.js';
import { userDocumentsRouter } from './user/documents.routes.js';
import { userLoyaltyRouter } from './user/loyalty.routes.js';
import { publicBlogBannersRouter } from './public/blog-banners.routes.js';
import { publicBlogsRouter } from './public/blogs.routes.js';
import { publicWebsiteLogosRouter } from './public/website-logos.routes.js';
import { publicMaintenanceModeRouter } from './public/maintenance-mode.routes.js';
import { publicWalletLogosRouter } from './public/wallet-logos.routes.js';

export const apiRouter = Router();

apiRouter.use(enforceMaintenanceMode);
apiRouter.use(healthRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/auth/verification', verificationRouter);
apiRouter.use('/user/dashboard', userDashboardRouter);
apiRouter.use('/user/deposits', userDepositsRouter);
apiRouter.use('/user/withdrawals', userWithdrawalsRouter);
apiRouter.use('/user/payment-accounts', userPaymentAccountsRouter);
apiRouter.use('/user/profile', userProfileRouter);
apiRouter.use('/user/documents', userDocumentsRouter);
apiRouter.use('/user/loyalty', userLoyaltyRouter);
apiRouter.use('/public/blog-banners', publicBlogBannersRouter);
apiRouter.use('/public/blogs', publicBlogsRouter);
apiRouter.use('/public/website-logos', publicWebsiteLogosRouter);
apiRouter.use('/public/maintenance-mode', publicMaintenanceModeRouter);
apiRouter.use('/public/wallet-logos', publicWalletLogosRouter);
apiRouter.use('/public/community-stats', publicCommunityStatsRouter);
apiRouter.use('/public/help-tickets', publicHelpTicketsRouter);
apiRouter.use('/public/promotional-banners', publicPromotionalBannersRouter);
apiRouter.use('/public/video-tutorials', publicVideoTutorialsRouter);
apiRouter.use('/public/loyalty/membership-tiers', publicLoyaltyMembershipTiersRouter);
apiRouter.use('/admin/dashboard', adminDashboardRouter);
apiRouter.use('/admin/performance', adminPerformanceRouter);
apiRouter.use('/admin/website-logos', adminWebsiteLogosRouter);
apiRouter.use('/admin/maintenance-mode', adminMaintenanceModeRouter);
apiRouter.use('/admin/message-templates', adminMessageTemplatesRouter);
apiRouter.use('/admin/bulk-sms', adminBulkSmsRouter);
apiRouter.use('/admin/auth', adminAuthRouter);
apiRouter.use('/admin/roles', adminRolesRouter);
apiRouter.use('/admin/system-users', adminSystemUsersRouter);
apiRouter.use('/admin/shifts', adminShiftsRouter);
apiRouter.use('/admin/customers', adminCustomersRouter);
apiRouter.use('/admin/blogs', adminBlogsRouter);
apiRouter.use('/admin/wallets', adminWalletsRouter);
apiRouter.use('/admin/pay-accounts', adminPayAccountsRouter);
apiRouter.use('/admin/payment-methods', adminPaymentMethodsRouter);
apiRouter.use('/admin/currency-types', adminCurrencyTypesRouter);
apiRouter.use('/admin/user-count-display', adminUserCountDisplayRouter);
apiRouter.use('/admin/rates', adminRatesRouter);
apiRouter.use('/admin/deposits', adminDepositsRouter);
apiRouter.use('/admin/withdrawals', adminWithdrawalsRouter);
apiRouter.use('/admin/scammers', adminScammersRouter);
apiRouter.use('/admin/reject-reasons', adminRejectReasonsRouter);
apiRouter.use('/admin/notifications', adminNotificationsRouter);
apiRouter.use('/admin/loyalty', adminLoyaltyRouter);
apiRouter.use('/admin/loyalty/membership-tiers', adminLoyaltyMembershipTiersRouter);
apiRouter.use('/admin/help-tickets', adminHelpTicketsRouter);
apiRouter.use('/admin/promotional-banners', adminPromotionalBannersRouter);
apiRouter.use('/admin/video-tutorials', adminVideoTutorialsRouter);

apiRouter.get('/', (_req, res) => {
  res.json({
    name: 'iTrustLD API',
    version: '1.0.0',
    docs: 'Add feature routes under /api/v1',
  });
});
