/** System template keys — assign in admin to override automatic notifications. */
export const MESSAGE_TEMPLATE_KEYS = {
  WELCOME_EMAIL: 'welcome_email',
  WELCOME_SMS: 'welcome_sms',
  ACCOUNT_VERIFICATION_EMAIL: 'account_verification_email',
  ACCOUNT_VERIFICATION_SMS: 'account_verification_sms',
  DEPOSIT_COMPLETED_EMAIL: 'deposit_completed_email',
  DEPOSIT_COMPLETED_SMS: 'deposit_completed_sms',
  DEPOSIT_REJECTED_EMAIL: 'deposit_rejected_email',
  DEPOSIT_REJECTED_SMS: 'deposit_rejected_sms',
  WITHDRAWAL_COMPLETED_EMAIL: 'withdrawal_completed_email',
  WITHDRAWAL_COMPLETED_SMS: 'withdrawal_completed_sms',
  WITHDRAWAL_REJECTED_EMAIL: 'withdrawal_rejected_email',
  WITHDRAWAL_REJECTED_SMS: 'withdrawal_rejected_sms',
  PASSWORD_RESET_EMAIL: 'password_reset_email',
  LOYALTY_LEVEL_UPGRADE_EMAIL: 'loyalty_level_upgrade_email',
  LOYALTY_REDEMPTION_APPROVED_EMAIL: 'loyalty_redemption_approved_email',
  LOYALTY_REDEMPTION_REJECTED_EMAIL: 'loyalty_redemption_rejected_email',
  LOYALTY_REDEMPTION_PENDING_EMAIL: 'loyalty_redemption_pending_email',
  KYC_APPROVED_EMAIL: 'kyc_approved_email',
  KYC_REJECTED_EMAIL: 'kyc_rejected_email',
  MANUAL_CONTACT_EMAIL: 'manual_contact_email',
  MANUAL_CONTACT_SMS: 'manual_contact_sms',
};

export const SYSTEM_TEMPLATE_KEY_OPTIONS = [
  { key: '', label: 'None (manual / reusable only)' },
  { key: MESSAGE_TEMPLATE_KEYS.WELCOME_EMAIL, label: 'Welcome email (registration)' },
  { key: MESSAGE_TEMPLATE_KEYS.WELCOME_SMS, label: 'Welcome SMS (registration)' },
  { key: MESSAGE_TEMPLATE_KEYS.ACCOUNT_VERIFICATION_EMAIL, label: 'Account verification email' },
  { key: MESSAGE_TEMPLATE_KEYS.ACCOUNT_VERIFICATION_SMS, label: 'Account verification SMS' },
  { key: MESSAGE_TEMPLATE_KEYS.DEPOSIT_COMPLETED_EMAIL, label: 'Deposit completed email' },
  { key: MESSAGE_TEMPLATE_KEYS.DEPOSIT_COMPLETED_SMS, label: 'Deposit completed SMS' },
  { key: MESSAGE_TEMPLATE_KEYS.DEPOSIT_REJECTED_EMAIL, label: 'Deposit rejected email' },
  { key: MESSAGE_TEMPLATE_KEYS.DEPOSIT_REJECTED_SMS, label: 'Deposit rejected SMS' },
  { key: MESSAGE_TEMPLATE_KEYS.WITHDRAWAL_COMPLETED_EMAIL, label: 'Withdrawal completed email' },
  { key: MESSAGE_TEMPLATE_KEYS.WITHDRAWAL_COMPLETED_SMS, label: 'Withdrawal completed SMS' },
  { key: MESSAGE_TEMPLATE_KEYS.WITHDRAWAL_REJECTED_EMAIL, label: 'Withdrawal rejected email' },
  { key: MESSAGE_TEMPLATE_KEYS.WITHDRAWAL_REJECTED_SMS, label: 'Withdrawal rejected SMS' },
  { key: MESSAGE_TEMPLATE_KEYS.PASSWORD_RESET_EMAIL, label: 'Password reset email' },
  { key: MESSAGE_TEMPLATE_KEYS.LOYALTY_LEVEL_UPGRADE_EMAIL, label: 'Loyalty level upgrade email' },
  { key: MESSAGE_TEMPLATE_KEYS.LOYALTY_REDEMPTION_APPROVED_EMAIL, label: 'Loyalty redemption approved email' },
  { key: MESSAGE_TEMPLATE_KEYS.LOYALTY_REDEMPTION_REJECTED_EMAIL, label: 'Loyalty redemption rejected email' },
  { key: MESSAGE_TEMPLATE_KEYS.LOYALTY_REDEMPTION_PENDING_EMAIL, label: 'Loyalty redemption pending email' },
  { key: MESSAGE_TEMPLATE_KEYS.KYC_APPROVED_EMAIL, label: 'KYC approved email' },
  { key: MESSAGE_TEMPLATE_KEYS.KYC_REJECTED_EMAIL, label: 'KYC rejected email' },
  { key: MESSAGE_TEMPLATE_KEYS.MANUAL_CONTACT_EMAIL, label: 'Manual customer email (default)' },
  { key: MESSAGE_TEMPLATE_KEYS.MANUAL_CONTACT_SMS, label: 'Manual customer SMS (default)' },
];
